BASE: ['']
TOOLBOX_MODE: "only_test"

TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  USE_LAST_EPOCH: False
  DATA:
    FS: 30
    DATASET: Custom
    DO_PREPROCESS: False
    DATA_FORMAT: NDCHW
    DATA_PATH: "raw_data"
    CACHED_PATH: "preprocessed_data"
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False
      RESIZE:
        H: 72
        W: 72

DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1

LOG:
  PATH: runs/inference_EfficientPhys_PURE

MODEL:
  DROP_RATE: 0.2
  NAME: EfficientPhys
  EFFICIENTPHYS:
    FRAME_DEPTH: 10

INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 10
  MODEL_PATH: "final_model_release/PURE_EfficientPhys.pth"
